name: Backend Tests

on:
  push:
    paths:
      - 'workoutapp-backend/**'
      - '.github/workflows/test-backend.yml'
  pull_request:
    paths:
      - 'workoutapp-backend/**'
      - '.github/workflows/test-backend.yml'

jobs:
  test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: workoutapp-backend

    env:
      NODE_ENV: test
      JWT_SECRET: testsecret
      MONGODB_URI: mongodb://localhost:27017/testdb

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Run backend tests
        run: npm test
